name: Update Random Quote

on:
  schedule:
    - cron: '0 */2 * * *' # Every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Run script
      run: |
        python generate_quote.py
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update random quote" || echo "No changes to commit"
        git push
